# Generated by Django 5.0 on 2024-10-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_dailyweathersummary_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyweathersummary',
            name='date',
        ),
    ]
