# Generated by Django 5.0 on 2024-10-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_dailyweathersummary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyweathersummary',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
