# Generated by Django 5.0 on 2024-10-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_dailyweathersummary_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature_threshold', models.FloatField()),
                ('condition_threshold', models.CharField(max_length=100)),
                ('consecutive_updates', models.IntegerField(default=2)),
            ],
        ),
    ]
