# Generated by Django 5.0 on 2024-10-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_weatherthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyweathersummary',
            name='humidity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyweathersummary',
            name='wind_speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherthreshold',
            name='humidity_threshold',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherthreshold',
            name='wind_speed_threshold',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherthreshold',
            name='consecutive_updates',
            field=models.IntegerField(default=3),
        ),
    ]
