# Generated by Django 5.0 on 2024-10-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_dailyweathersummary_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='wind_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherthreshold',
            name='humidity_threshold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherthreshold',
            name='wind_speed_threshold',
            field=models.FloatField(default=0),
        ),
    ]
