# Generated by Django 5.0 on 2024-10-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_alter_dailyweathersummary_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherthreshold',
            name='alert_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
